nickgenerator/urls.py
from django.urls import path

from . import views

app_name = "nickgenerator"

urlpatterns = [
    path('', views.index, name = 'index'), 
    path('latest', views.latest, name = 'latest'),
    path('best', views.best, name = 'best'),
    path('<slug:nick_title>', views.details, name = 'nick'),
    path('like/<slug:nick_title>', views.like, name = 'like')
]

nickhunter/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('generate/', include('nickgenerator.urls')),
    path('admin/', admin.site.urls),
]

nickgenerator/models.py
from django.db import models

class Nick(models.Model):
    title = models.CharField(max_length = 64)
    date = models.DateTimeField('date generated')
    rating = models.IntegerField(default = 0)

    def __str__(self):
        return '%s created %s' % (self.title, str(self.date))

class Like(models.Model):
    ip_address = models.CharField(max_length = 20)
    nick_title = models.CharField(max_length = 64)
    
    def __str__(self):
        return '%s liked %s' % (self.ip_address, self.nick_title)

nickgenerator/views.py
# standard

import random

# urllib

from urllib.request import urlopen
from urllib.error import HTTPError

# django

from django.http import HttpResponse
from django.utils import timezone
from django.shortcuts import render, redirect
from django.template import loader
from django.http import Http404

# local

from .models import Nick, Like
from .converters import get_time_ago, date_to_string, make_short_dates, make_long_dates
from .generators import get_new_nick
from .adapters import is_vk_free, is_github_free
from .utils import is_liked, get_client_ip, try_find_nick


def index(request):
    latest_nicks = make_short_dates(Nick.objects.order_by('-date')[:5])
    best_nicks = make_short_dates(Nick.objects.order_by('-rating')[:5])
    
    new_nick = get_new_nick()
    
    context = {
            'latest_nicks': latest_nicks, 
            'top_nicks': best_nicks, 
            'generated_nick': new_nick,
            'vk_free': is_vk_free(new_nick),
            'github_free': is_github_free(new_nick),
            'is_liked': is_liked(request, new_nick)
    }
    
    new_nick_object = Nick(title = new_nick, date = timezone.now())
    new_nick_object.save()

    return render(request, 'nickgenerator/index.html', context)


def details(request, nick_title):
    required_nick = try_find_nick(nick_title)
    
    latest_nicks = make_short_dates(Nick.objects.order_by('-date')[:5])
    best_nicks = make_short_dates(Nick.objects.order_by('-rating')[:5])

    context = {
            'latest_nicks': latest_nicks, 
            'top_nicks': best_nicks, 
            'generated_nick': required_nick.title,
            'vk_free': is_vk_free(required_nick.title),
            'github_free': is_github_free(required_nick.title),
            'date': required_nick.date,
            'rating': required_nick.rating, 
            'is_liked': is_liked(request, nick_title)
    }

    return render(request, 'nickgenerator/index.html', context)


def like(request, nick_title):
    required_nick = try_find_nick(nick_title)
    
    appendix = 1

    try:
        required_like = Like.objects.get(nick_title = nick_title, ip_address = get_client_ip(request))
    except Like.DoesNotExist:
        like = Like(nick_title = nick_title, ip_address = get_client_ip(request))
        like.save()
    else:
        required_like.delete() 
        appendix = -1

    required_nick.rating = required_nick.rating + appendix;
    required_nick.save()

    return redirect('nickgenerator:nick', nick_title = nick_title)


def latest(request):
    nicks = make_long_dates(Nick.objects.order_by('-date'))
    context = {'nicks': nicks, 'header': 'Latest nicks'}
    return render(request, 'nickgenerator/all.html', context)


def best(request):
    nicks = make_long_dates(Nick.objects.order_by('-rating'))
    context = {'nicks': nicks, 'header':'Best nicks'}
    return render(request, 'nickgenerator/all.html', context)


def no_such_page(request):
    return HttpResponse("404 - there is no such page on this site")

nickgenerator/templates/nickgenerator/all.html
<!doctype html>

{% load static %}

<html lang="en">
    <head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Nickhunter</title>

	<!-- Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=M+PLUS+1p:300" rel="stylesheet">


	<!-- Styles -->
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'nickgenerator/general.css' %}">

    </head>
    <body>
	<div class="full-height">
	    <div class="content">
		{% if header %}
		<div class="title up-text">
			{{header}}
		</div>
		{% endif %}
		<div class="controls">
			<a href="{% url 'nickgenerator:index' %}">&lt;back&gt;</a>
		</div>
		<div class = "list-container">
			{% if nicks %}
				{% for nick in nicks %}
				<a href = "{% url 'nickgenerator:nick' nick.title %}">{{nick.title}}</a>&nbsp;&nbsp;{{nick.date}}&nbsp;&nbsp;{{nick.rating}}<br/>
				{% endfor %}
			{% else %}
				<p>No nicks available</p>
			{% endif %}
		</div>
	    </div>
	</div>
    </body>
</html>

nickgenerator/templates/nickgenerator/index.html
<!doctype html>

{% load static %}

<html lang="en">
    <head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Nickhunter</title>

	<!-- Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=M+PLUS+1p:300" rel="stylesheet">


	<!-- Styles -->
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'nickgenerator/general.css' %}">

    </head>
    <body>
	<div class="flex-center position-ref full-height">
	    <div class="content">
		{% if date %}
		<div class="title up-text">
			Generated&nbsp;{{date}}&nbsp;|&nbsp;{{rating}}&nbsp;liked
		</div>
		{% endif %}
		<div class="controls">
			<a href="{% url 'nickgenerator:like' generated_nick %}">&lt;{% if is_liked %}dislike{% else %}like{% endif %}&gt;</a>
			&nbsp;&nbsp;
			<a href="{% url 'nickgenerator:index' %}">&lt;new&gt;</a>
		</div>
		<div class="new-nick up-text">
			<span>{{generated_nick}}</span>
		</div>
		<div class='checking-results'>
		<div class="checking-result {%if vk_free %}result-free{% else %}result-busy{% endif %}">
			<a href="http://vk.com/{{generated_nick}}">vk</a>&nbsp;is
			{% if vk_free %}free{% else %}busy{% endif %}
		</div>	
		<div class="checking-result {%if github_free%}result-free{% else %}result-busy{% endif %}"  style='margin-left:80px;'>
			<a href="http://github.com/{{generated_nick}}">github</a>&nbsp;is
			{% if github_free %}free{% else %}busy{% endif %}
		</div>
		</div>
		<div class='list-containers'>
		<div class = "list-container">
			<h3><a href="{% url 'nickgenerator:latest' %}">Latest nicks</a></h3>
			{% if latest_nicks %}
				{% for nick in latest_nicks %}
					<a href = "{% url 'nickgenerator:nick' nick.title %}">{{nick.title}}</a>&nbsp;&nbsp;{{nick.date}}<br/>
				{% endfor %}
			{% else %}
				<p>No latest nicks available</p>
			{% endif %}
		</div>
		<div class= "list-container" style="margin-left: 80px;">
			<h3><a href="{% url 'nickgenerator:best' %}">Best nicks</a></h3>
			{% if top_nicks %}
				{% for nick in top_nicks %}
					<a href = "{% url 'nickgenerator:nick' nick.title %}">{{nick.title}}</a>&nbsp;&nbsp;{{nick.rating}}<br/>
				{% endfor %}
			{% else %}
				<p>No top nicks available</p>
			{% endif %}
		</div>
		</div>
	    </div>
	</div>
    </body>
</html>